### ISSUE TITLE
precession rate

### ISSUE THREAD

**Issue by macgrac** [stefano-meschiari/Systemic2#12]
Hi Stefano,

Many thanks for the new version (2.18) of Systemic. 
The precession rate is a great feature. I noticed however that it works in the Keplerian approach only, not with dynamical integrators.

Best,
Gracjan

**Comment by stefano-meschiari** [comment]
Hi Gracjan,

Thanks! This is intended — in the keplerian integrator, I simply have to add a time-dependent term to the periastron. In the dynamical integrator the evolution is computed in cartesian coordinates, and I can't think of a way to add the precession manually in a consistent manner.
