### ISSUE TITLE
Problems compiling the new version?

### ISSUE THREAD

**Issue by Trifonoff** [stefano-meschiari/Systemic2#16]
Hi Stefano!

I have some problems installing your last Systemic version on Linux. First of all I don't see Systemic.sh and SystemicGui.jar in the unzipped directory. $> make -f Makefile.linux seems to not work for me.
Any ideas? Have you tried to compile Systemic2-master on Linux machine? I don't have any problems with earlier versions.

**Comment by Trifonoff** [comment]
Actually, I guess I my installation is not going well and I am wondering why... let me see....

**Comment by stefano-meschiari** [comment]
Hey,

The "master" branch from GitHub are work-in-progress versions of the C and R code alone. It doesn't include the GUI or any of the dependencies. I would recommend using the .tar.gz distributions on my website (http://www.stefanom.org/d/systemic2/).

I am trying to release a new version with the functionality available in the master branch pretty soon, but I'm tied up with work as usual :)
