### ISSUE TITLE
package ‘rdyncall’ is not available (for R version 3.1.1)

### ISSUE THREAD

**Issue by macdui99** [stefano-meschiari/Systemic2#8]
Hi,

I am trying to compile Systemic 2.1730 on Fedora 20 with R version 3.1.1 but encounter the following problem concerning rdyncall when installing R packages

I run:     make -f Makefile.linux

Here is the output for the section installing R packages up to the rdyncall message:

echo "Installing R packages"
Installing R packages
/usr/bin/R --vanilla --interactive --no-save < R/install.r

R version 3.1.1 (2014-07-10) -- "Sock it to Me"
Copyright (C) 2014 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages('rdyncall', repos="http://cran.us.r-project.org")
Installing package into ‘/home/jbarnes/R/x86_64-redhat-linux-gnu-library/3.1’
(as ‘lib’ is unspecified)
Warning message:
package ‘rdyncall’ is not available (for R version 3.1.1) 
------------------------------------------------------------------------

All else seems to install fine and libsystemic.so is created in both the Systemic and Systemic R directories.

When I run Systemic via 

sh Systemic.sh

I get a long series of error messages in red:

Installing package into ‘/home/jbarnes/R/x86_64-redhat-linux-gnu-library/3.1’
(as ‘lib’ is unspecified)
Loading required package: rdyncall
Error in eval(expr, envir, enclos) : 
  could not find function "parseStructInfos"
Calls: source ... withVisible -> eval -> eval -> sys.source -> eval -> eval
In addition: Warning messages:
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘rdyncall’
2: In .require.library("rdyncall") : Installing package  rdyncall 

3: package ‘rdyncall’ is not available (for R version 3.1.1) 
4: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘rdyncall’
Execution halted

I have tried adding

'Systemic' directory, 'Systemic/R' directory and 'R' install directory to LD_LIBRARY_PATH to no avail.

I have also tried editing 

R=/usr/bin/R   in  pref.tex

To any of the above directories, which doesn't work. 

Setting to the installed 'R' packages location removes the error messages, but as in all instances, the GUI also has the persistent -in progress- animation bar and the message: 'Systemic is booting up, please wait ...' message

I don't seem to be able to do anything other than browse data files.

Is this really an issue with missing rdyncall in 3.1.1 (do I need an earlier version?) or have I missed something else?

Many thanks,
John Barnes

**Comment by ddellaro** [comment]
I’m trying to run Systemic on my Mac (Yosemite OS X 10.9.4).  I encountered the rdyncall package problem, and read through the associated posts above.  I’ve downloaded rdyncall_0.7.5.tar.gz from the CRAN archive as suggested, but, just like Tom Kosvic states, I don’t feel comfortable trying to build the rdyncall package on my MAC without guidance.  Any help with this build would be much appreciated!

Best Regards,
Devin Della-Rose

**Comment by stefano-meschiari** [comment]
Try to run the pre-release version at http://stefanom.org/d/systemic2 — it includes rdyncall and should install it automatically.

**Comment by ddellaro** [comment]
Hello Stefano, and thanks for the quick reply!  Yesterday evening I figured out how to install rdyncall (using Trifon's suggestion above), and now version 2.173 is working fine!  Do you recommend that I upgrade to version 2.18 now, or is the pre-release version likely to get some minor mods between now & general release?

Thanks again,
Devin

**Comment by stefano-meschiari** [comment]
Hi Devin,

There are some bugfixes in 2.18 (nothing that should be too important) but potentially new bugs as well — that’s why I labeled it pre-release for now :)  I’m trying to get 2.18 out in February.

**Comment by JohnMCollins** [comment]
I tried all that but it complains that rdyncall was built with a previous version of R to that which I'm running on Ubuntu 14.04 and still crashes.
Any way round that?
